# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [2]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [4]:
A = np.arange(1, 16).reshape(3,5)

In [10]:
print(A.ndim)
print(A.shape)
print(A.size)
print(A.data)
print(type(A))

2
(3, 5)
15
<class 'numpy.ndarray'>


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [20]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [19]:
D = B - C

print(D)

E = B * C

print(E)

F = B @ C

print (F)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [21]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
J = np.exp(B)

print(J)
print(B.min())
print(B.min(1))
print(B.min(0))
print(B.argmin())
print(B.argmin(1))
print(B.argmin(0))

print(B.sum())
print(B.mean(0))

median_for_b = np.median(B, 0)
print(median_for_b)



[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
1
[1 4 7]
[1 2 3]
0
[0 0 0]
[0 0 0]
45
[4. 5. 6.]
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [49]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [50]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

A[1] specifies that you are subsetting at and the entire row 1 (start count from 0, so second row in array)

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [51]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [52]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [53]:
for i in np.nditer(A):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [77]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()
print(b)

c = b.reshape(1, 3, -1)
print("start:", c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
start: [[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]
  [20 21 22 23 24 25 26 27 28 29]]]


It specifies how many rows the array will have. <br>
We create an array from numpy using the arrange method from 0 to 30. <br>
We declare a new variable b that has a's values but shaped into an array with 3 rows <br>

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [79]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1)
print(m2)
print(m1 + m2)

[[1 2]
 [3 4]]
[1 1]
[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [80]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [81]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [150]:

def add_mult_matrices(a, b, c):
    if not isinstance(a, np.ndarray) or not isinstance(b, np.ndarray):
        raise TypeError("Both inputs must be numpy arrays.")
    
    a_rows, a_cols = a.shape
    b_rows, b_cols = b.shape
    
    if c == "add":
        if a.shape == b.shape:  
            return a + b
        else:
            raise ValueError("Matrices must have the same shape for addition.")

    elif c == "multiply":
        if a_cols == b_rows: 
            return np.dot(a, b)  
        else:
            raise ValueError("Number of columns in A must equal number of rows in B for multiplication.")
    
    else:
        raise ValueError("Invalid operation. Use 'add' or 'multiply'.")

v3 = np.arange(1, 10).reshape(3, 3)
v4 = np.arange(1, 10).reshape(3, 3)

print("V3:", v3)
print("")
print("V4:", v4)
print("")
print(add_mult_matrices(v3, v4, "add"))
print("")
print(add_mult_matrices(v3, v4, "multiply"))
print("")

v5 = np.arange(1, 7).reshape(2, 3)
v6 = np.arange(5,14).reshape(3, 3)

print("V5:", v5)
print("")
print("V6:", v6)
print("")
(print(add_mult_matrices(v5, v6, "multiply")))

V3: [[1 2 3]
 [4 5 6]
 [7 8 9]]

V4: [[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

V5: [[1 2 3]
 [4 5 6]]

V6: [[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]

[[ 54  60  66]
 [126 141 156]]


In [ ]:
#def add_mult_matrices(a, b, c):
  #  a_rows, a_cols = a.shape
   # b_rows, b_cols = b.shape
    
  #  if a and b != isinstance(np.ndarray()):
   #     return TypeError
  #  elif c == "add" and a.shape == b.shape:
  #       return a+b
  #  elif c == "multiply" and a_rows == b_cols:
  #      return a*b
 #  else:
  #      raise Exception("Check size of arrays and validate add or multiply argument")
    
    
#v3 = np.array[1,2,3]
#v4 = np.array[2,3,4]

#add_mult_matrices(v3, v4, "add")


In [ ]:
##def add_mult_matrices(a, b, c):
    #a_rows, a_cols = a.shape
    #b_rows, b_cols = b.shape
    
    #if a and b == isinstance(np.ndarray()) and c == "add" and a.ndarray.size == b.ndarray.size:
        #return a+b
    #elif a and b == isinstance(np.ndarray() and c == "multiply") and a_rows == b_cols:
        #return a*b
    #else:
       # raise Exception('Expected "add" or "multiply" as third argument')
    

##v3 = np.array[1,2,3]
##v4 = np.array[2,3,4]

##add_mult_matrices(v3, v4, "add")

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [21]:
##Övningsuppgifter 10.1.1

x = np.array([4, 3])

#a) Dimension 1x2
#b)
print(5*x)
#c)
print(3*x)
#d)
print((5 * x) + (3 * x))
#e)
print(8*x)
#f)
print((4 * x) - (x))
#g) Dimension 2x1
#h) Ej definierat
#i)
print(np.linalg.norm(x))


##Övningsuppgifter 10.1.2

v = np.array([3,7,0,11]).reshape(4,1)
print(v)
#a) Dimension 4x1
#b)
print(v * 2)
#c)
print((5*v) + (2*v))
#d)
print((4*v) - (2*v))
#e) Nya dimension blir 1x4
print(np.transpose(v))
#f)
print(np.linalg.norm(v))

##Övningsuppgifter 10.1.3
v1 = np.array([4,3,1,5])
v2 = np.array([2,3,1,1])
#a)
print(np.linalg.norm(v1))
#b)
print(np.linalg.norm((v1-v2)))

[20 15]
[12  9]
[32 24]
[32 24]
[12  9]
5.0
[[ 3]
 [ 7]
 [ 0]
 [11]]
[[ 6]
 [14]
 [ 0]
 [22]]
[[21]
 [49]
 [ 0]
 [77]]
[[ 6]
 [14]
 [ 0]
 [22]]
[[ 3  7  0 11]]
13.379088160259652
7.14142842854285
4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [46]:
##Övningsuppgifter 10.2.1

A = np.array([2,1,-1,1,-1,1]).reshape(2,3)
B = np.array([4,-2,1,2,-4,-2]).reshape(2,3)
C = np.array([1,2,2,1]).reshape(2,2)
D = np.array([3,4,4,3]).reshape(2,2)
E = np.array([1,2]).reshape(2,1)
I = np.array([1,0,0,1]).reshape(2,2)

#a)
print(2*A)
#b)
print(B-(2*A))
#c)
#Ej Definerat
#d)
(2*D) - (3*C)
#e)
print(np.transpose(D) + (2*D))
#f)
print((2*np.transpose(C)-(2*np.transpose(D))))
#g)
#Ej Definerat
#h)
#Ej Definerat
#i)
print(C@D)
#j)
print(C@B)
#k)
print(C@I)
#l)
print(A@np.transpose(B))

##Övningsuppgifter 10.2.2

A2 = np.array([2,3,4,5,4,1]).reshape(2,3)

print(A2@np.transpose(A2))

##Övningsuppgifter 10.2.3

A3 = np.array([1,2,2,4]).reshape(2,2)
B2 = np.array([2,1,1,3]).reshape(2,2)
C2 = np.array([4,3,0,2]).reshape(2,2)

result1 = A3@B2
result2 = A3@C2

if  np.array_equal(result1, result2):
    print("True")
else:
    print("False")
    
if np.array_equal(B2, C2):
    print("True")
else:
    print("False")

[[ 4  2 -2]
 [ 2 -2  2]]
[[ 0 -4  3]
 [ 0 -2 -4]]
[[ 9 12]
 [12  9]]
[[-4 -4]
 [-4 -4]]
[[11 10]
 [10 11]]
[[  8 -10  -3]
 [ 10  -8   0]]
[[1 2]
 [2 1]]
[[5 2]
 [7 4]]
[[29 26]
 [26 42]]
True
False


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [132]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

v2[-1] = 123
print(v2)
print(v1)

print(v1.base)
print(v2.base)
print(np.may_share_memory(v1, v2))

[0 1 2 3]
[2 3]
[  2 123]
[  0   1   2 123]
None
[  0   1   2 123]
True


Because v2 is not a separate copy and it is a view if v1. When we set v2[-1] = 123 we are actually changing v1[3]

In [131]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[  0   1   2 123]


In [133]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
